name: Create Tag on Merged PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create_tag_if_pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - name: Setup GIT Config User
        run: |
         git config user.name "${{ github.actor }}"
         git config user.email "${{ github.actor }}@users.noreply.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store last commit message
        run: |
         echo "LAST_COMMIT=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_ENV"
      - name: Debug commit message
        run: |
          echo "${{ env.LAST_COMMIT }}"
      - name: Create tag
        run: |
          if echo "${{ env.LAST_COMMIT }}" | grep -qE -- "--patch"; then
            echo "Patch tag detected. Creating patch tag..."
            npm run semver:patch
          elif echo "${{ env.LAST_COMMIT }}" | grep -qE -- "--minor"; then
            echo "Minor tag detected. Creating minor tag..."
            npm run semver:minor
          elif echo "${{ env.LAST_COMMIT }}" | grep -qE -- "--major"; then
            echo "Major tag detected. Creating major tag..."
            npm run semver:major
          else
            echo "No semver:flag detected. Defaulting to patch tag..."
            npm run semver:patch
          fi
      - name: Debug tag creation
        run: npm run tag:debug
      - name: Push automated commit
        run: git push origin main
      - name: Push tag to GitHub
        run: npm run tag:push