name: Create Tag on Merged PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create_tag_if_pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup GIT Config User
        run: |
         git config user.name "${{ github.actor }}"
         git config user.email "${{ github.actor }}@users.noreply.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store last commit message
        run: |
         echo "LAST_COMMIT=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_ENV"
      - name: Debug commit message
        run: |
          echo "${{ env.LAST_COMMIT }}"
      - name: Create tag
        run: |
          if echo "${{ env.LAST_COMMIT }}" | grep -qE -- "--minor"; then
            echo "Minor semver flag detected. Creating minor tag..."
            npm run semver:minor
          elif echo "${{ env.LAST_COMMIT }}" | grep -qE -- "--major"; then
            echo "Major semver flag detected. Creating major tag..."
            npm run semver:major
          else
            echo "No semver flag detected. Defaulting to patch tag..."
            npm run semver:patch
          fi
      - name: Push automated commit
        run: git push origin main
      - name: Push tag to GitHub with secret
        run: npm run tag:push:ci
      - name: Dispatch Ref to workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/.github/workflows/change-mgmt.yml/dispatches \
            -d '{"ref":"main"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
